#!/bin/bash

# * This script is intended to be run after a clean install of DietPi as the root user. It configures the DietPi environment to run DashLab Software.

echo "*** This script is intended to be run after a clean install of DietPi as the root user. It configures the DietPi environment to run DashLab Software ***"
echo 

# Check if running as root user
if [ "$EUID" -ne 0 ]
  then echo "Please run this script on a clean DietPi installation as root"
  exit
fi

# Create dashlab user
./addUnixUser.sh dashlab dashlab

# Add dashlab user to groups
./addUserToGroup.sh dashlab

# Install dependencies and DietPi software
./installDeps.sh

# ! DISABLED
# The script below is designed to append some lines to the specified user's .profile to start xorg and add sbin to PATH, but since I'm not sure if .profile is generated by adduser or after first login I've disabled it for now.
#./setupUserProfile.sh dashlab


